#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           servoMotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title: Output Output Output
  Team Members: Raymond Metzger, Ryan Potter, Robbie Vannucchi, Nick Franzwa
  Date: 2/1/19
  Section: A3_1_2 Part 3


  Task Description:


  Pseudocode:

*/

task main()
{                                     //Program begins, insert code within curly braces

motor[port2] = 63.5;
wait1Msec(5000);
stopMotor(port2);
//rotates the right motor in a positive direction at half speed for 5 seconds

motor[port3] = -127/4;
wait1Msec(2500);
stopMotor(port3);
wait1Msec(2000);
//rotates the left motor in a negative driection at quarter speed for 2.5 seconds

motor[port2] = 127;
motor[port3] = 127;
wait1Msec(7250);
stopMotor(port2);
stopMotor(port3);
//rotates both motors at full speed for 7.25 seconds

}
