#pragma config(Sensor, dgtl12, red,            sensorLEDtoVCC)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           servoMotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title: Start Both Motors
  Team Members: Raymond Metzger, Ryan Potter, Robbie Vannucchi, Nick Franzwa
  Date: 2/1/19
  Section: A3_1_2 Part 2


  Task Description:
  Start both motors at half speed, then rotate them the other way at half speed.

  Pseudocode:
  Start both motors at half speed clockwise
  wait 5 seconds
  stop both motors
  Start both motors at half speed counterclockwise
*/

task main()
{                                     //Program begins, insert code within curly braces

motor[port2] = 63.5; // start right motor at half speed
motor[port3] = 63.5; // start left motor at half speed
wait1Msec(5000); // wait 5 seconds
stopMotor(port2); // stop right motor
stopMotor(port3); // stop left motor
//this rotates the right motor and left motor at half speed for 5 seconds, then stops it
motor[port2] = -63.5; // start right motor at half speed rotating the other way
motor[port3] = -63.5; // start left motor at half speed rotating the other way
wait1Msec(5000); // wait 5 seconds
stopMotor(port2); // stop right motor
stopMotor(port3); // stop left motor
//This section reverses the motors, then stops them again




}
