#pragma config(Sensor, dgtl8,  red,            sensorLEDtoVCC)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title: Output Output Output
  Team Members: Raymond Metzger, Ryan Potter, Robbie Vannucchi, Nick Franzwa
  Date: 2/1/19
  Section: A3_1_2


  Task Description:


  Pseudocode: The red led will turn off, wait one second, turn on, wait one second, turn off, wait one second, turn on, wait one second, and turn off.

*/

task main()
{                                     //Program begins, insert code within curly braces
	turnLEDOff(red); //Turn off led 
	wait(1);         //Wait 1 sec 
	turnLEDOn(red);  //Turn on led
	wait(1);         //Wait 1 sec 
	turnLEDOff(red); //Turn off led 
	wait(1);         //Wait 1 sec 
	turnLEDOn(red);  //Turn on led
	wait(1);         //Wait 1 sec
	turnLEDOff(red); //Turn off led 




}
