#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           servoMotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title: Output Output Output
  Team Members: Raymond Metzger, Ryan Potter, Robbie Vannucchi, Nick Franzwa
  Date: 2/1/19
  Section: A3_1_2 Part 3


  Task Description:


  Pseudocode:

*/

task main()
{                                     //Program begins, insert code within curly braces

motor[port2] = 63.5; //Right motor -cw- at half speed
wait1Msec(5000);     //Wait 5 seconds
stopMotor(port2);    //stop right motor
//rotates the right motor in a positive direction at half speed for 5 seconds

motor[port3] = -127/4; //Left motor -ccw- at 1/4 speed
wait1Msec(2500);       //Wait 2.5 seconds
stopMotor(port3);      //Stop right motor 
wait1Msec(2000);       //Wait 2 seconds
//rotates the left motor in a negative driection at quarter speed for 2.5 seconds

motor[port2] = 127;   //Right motor full speed
motor[port3] = 127;   //Left motor full speed
wait1Msec(7250);      //Wait 7.25 seconds
stopMotor(port2);     //Stop right motor
stopMotor(port3);     //Stop left motor
//rotates both motors at full speed for 7.25 seconds

}
