#pragma config(Sensor, dgtl12, red,            sensorLEDtoVCC)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           servoMotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title: Output Output Output
  Team Members: Raymond Metzger, Ryan Potter, Robbie Vannucchi, Nick Franzwa
  Date: 2/1/19
  Section: A3_1_2 Part 2


  Task Description:


  Pseudocode:

*/

task main()
{                                     //Program begins, insert code within curly braces

motor[port2] = 63.5;
motor[port3] = 63.5;
wait1Msec(5000);
stopMotor(port2);
stopMotor(port3);
//this rotates the right motor and left motor at half speed for 5 seconds, then stops it
motor[port2] = -63.5;
motor[port3] = -63.5;
wait1Msec(5000);
stopMotor(port2);
stopMotor(port3);
//This section reverses the motors, then stops them again




}
