#pragma config(Sensor, dgtl8,  red,            sensorLEDtoVCC)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title: Output Output Output
  Team Members: Raymond Metzger, Ryan Potter, Robbie Vannucchi, Nick Franzwa
  Date: 2/1/19
  Section: A3_1_2


  Task Description:


  Pseudocode:

*/

task main()
{                                     //Program begins, insert code within curly braces
	turnLEDOff(red);
	wait(1);
	turnLEDOn(red);
	wait(1);
	turnLEDOff(red);
	wait(1);
	turnLEDOn(red);
	wait(1);
	turnLEDOff(red);




}
